version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: trive-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sukses121
      POSTGRES_DB: trive_db
    ports:
      - "5432:5432"
    volumes:
      - trive-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  trive-postgres-data:

